import { Equipment } from "@/types";
import {
  LucideAnvil,
  LucideArmchair,
  LucideArrowBigUpDash,
  LucideArrowRight,
  LucideAtom,
  LucideBattery,
  LucideBatteryCharging,
  LucideBed,
  LucideBolt,
  LucideBox,
  LucideBoxes,
  LucideBuilding,
  LucideBuilding2,
  LucideCableCar,
  LucideCastle,
  LucideChurch,
  LucideCircleDot,
  LucideClock,
  LucideCode,
  LucideCompass,
  LucideCpu,
  LucideCrown,
  LucideDoorOpen,
  LucideDrill,
  LucideDroplet,
  LucideFastForward,
  LucideGem,
  LucideGraduationCap,
  LucideHospital,
  LucideHouse,
  LucideLayers,
  LucideLeaf,
  LucideLink,
  LucideMagnet,
  LucideMapPin,
  LucideMicroscope,
  LucideMountain,
  LucideNetwork,
  LucidePersonStanding,
  LucidePickaxe,
  LucidePlaneTakeoff,
  LucidePresentation,
  LucideRadar,
  LucideRocket,
  LucideRotate3D,
  LucideSatelliteDish,
  LucideShield,
  LucideShieldAlert,
  LucideShieldCheck,
  LucideShip,
  LucideSignal,
  LucideSmile,
  LucideSun,
  LucideSword,
  LucideTableCellsSplit,
  LucideTentTree,
  LucideThermometer,
  LucideTrain,
  LucideWind,
} from "lucide-react";

export const EQUIPMENT_LIST: Record<string, Equipment> = {
  crew: {
    name: "Crew Member",
    description:
      "Adds another member to your crew, increasing your AU per click.",
    baseCost: 15,
    costMultiplier: 1.07,
    auPerSecond: 1,
    threshold: 20,
    buildTime: 3,
    equipment: false,
    icon: LucidePersonStanding,
    mapPosition: {
      x: 60,
      y: 50,
    },
    upgrades: {
      training: {
        name: "Training",
        description: "Train your crew members to more efficiently operate.",
        cost: 2500,
        multiplier: 0.3,
        maxCount: 20,
        threshold: 3,
        icon: LucideGraduationCap,
      },
      moraleBoost: {
        name: "Morale Boost",
        description: "Increase the morale of your crew, boosting productivity.",
        cost: 7000,
        multiplier: 0.25,
        maxCount: 10,
        threshold: 8,
        icon: LucideSmile,
      },
      equipmentUpgrade: {
        name: "Equipment Upgrade",
        description:
          "Provide better tools for your crew, enhancing efficiency.",
        cost: 10000,
        multiplier: 0.4,
        maxCount: 10,
        threshold: 12,
        icon: LucideBolt,
      },
      automation: {
        name: "Crew Automation",
        description:
          "Implement AI-assisted workflows to maximize crew productivity.",
        cost: 18000,
        multiplier: 0.5,
        maxCount: 5,
        threshold: 20,
        icon: LucideCpu,
      },
    },
  },
  charter: {
    name: "Charter a Billionaire",
    description: "Show some billionaire Earth from space.",
    baseCost: 100,
    costMultiplier: 1.09,
    auPerSecond: 8,
    threshold: 30,
    buildTime: 5,
    icon: LucidePlaneTakeoff,
    mapPosition: {
      x: 59,
      y: 55,
    },
    upgrades: {
      seats: {
        name: "Additional Seats",
        description: "Increase your carrying capacity.",
        cost: 1500,
        multiplier: 0.3,
        maxCount: 5,
        threshold: 4,
        icon: LucideArmchair,
      },
      crew: {
        name: "Crew Members",
        description: "Add more crew members to speed up research.",
        cost: 2500,
        multiplier: 0.35,
        maxCount: 5,
        threshold: 8,
        icon: LucidePersonStanding,
      },
      marketing: {
        name: "Marketing Budget",
        description: "Increase the marketing budget to scam more billionaires.",
        cost: 3500,
        multiplier: 0.4,
        maxCount: 5,
        threshold: 12,
        icon: LucidePresentation,
      },
      luxury: {
        name: "Luxury Amenities",
        description: "Add premium features to attract higher-paying clients.",
        cost: 5000,
        multiplier: 0.55,
        maxCount: 3,
        threshold: 16,
        icon: LucideCrown,
      },
    },
  },
  miningRig: {
    name: "Asteroid Mining Rig",
    description: "Mine asteroids around the galaxy to earn AU.",
    baseCost: 1100,
    costMultiplier: 1.1,
    auPerSecond: 12,
    threshold: 300,
    buildTime: 12,
    icon: LucidePickaxe,
    mapPosition: {
      x: 56,
      y: 60,
    },
    upgrades: {
      cargo_capacity: {
        name: "Cargo Capacity",
        description: "Increase the Mining Rig's load capacity.",
        cost: 6000,
        multiplier: 0.22,
        maxCount: 8,
        threshold: 4,
        icon: LucideBoxes,
      },
      boosters: {
        name: "Rocket Boosters",
        description: "Increase the mining rig's travel speed.",
        cost: 8500,
        multiplier: 0.35,
        maxCount: 5,
        threshold: 8,
        icon: LucideArrowBigUpDash,
      },
      drill: {
        name: "Drill Efficiency",
        description: "Increase the efficiency of the drill bit.",
        cost: 12500,
        multiplier: 0.5,
        maxCount: 3,
        threshold: 12,
        icon: LucideDrill,
      },
      asteroid_detection: {
        name: "Asteroid Detection System",
        description: "Advanced radar system to locate resource-rich asteroids.",
        cost: 16500,
        multiplier: 0.6,
        maxCount: 3,
        threshold: 16,
        icon: LucideRadar,
      },
    },
  },
  satellite: {
    name: "Satellite Network",
    description:
      "Deploy satellites to enhance communication and resource gathering.",
    baseCost: 5500,
    costMultiplier: 1.11,
    auPerSecond: 18,
    threshold: 1800,
    buildTime: 20,
    icon: LucideSatelliteDish,
    mapPosition: {
      x: 51,
      y: 62,
    },
    upgrades: {
      solarPanels: {
        name: "Solar Panels",
        description: "Increase energy efficiency of the satellites.",
        cost: 12000,
        multiplier: 0.22,
        maxCount: 8,
        threshold: 4,
        icon: LucideSun,
      },
      dataProcessing: {
        name: "Data Processing Units",
        description: "Improve data collection and analysis.",
        cost: 16500,
        multiplier: 0.35,
        maxCount: 5,
        threshold: 8,
        icon: LucideCpu,
      },
      thrusters: {
        name: "Advanced Thrusters",
        description: "Enable satellites to reposition faster.",
        cost: 23000,
        multiplier: 0.5,
        maxCount: 3,
        threshold: 12,
        icon: LucideRocket,
      },
      network_expansion: {
        name: "Network Expansion",
        description: "Increase your satellite coverage across space.",
        cost: 29000,
        multiplier: 0.65,
        maxCount: 2,
        threshold: 16,
        icon: LucideNetwork,
      },
    },
  },
  exploration: {
    name: "Exploration",
    description: "Explore other galaxies in search of precious metals.",
    baseCost: 3800,
    costMultiplier: 1.11,
    auPerSecond: 22,
    threshold: 1000,
    icon: LucideRocket,
    buildTime: 18,
    mapPosition: {
      x: 45,
      y: 62,
    },
    upgrades: {
      boosters: {
        name: "Rocket Boosters",
        description: "Increase the exploration ship's travel speed.",
        cost: 8500,
        multiplier: 0.22,
        maxCount: 5,
        threshold: 4,
        icon: LucideArrowBigUpDash,
      },
      crew: {
        name: "Crew Members",
        description: "Add more crew members to help around the ship.",
        cost: 12000,
        multiplier: 0.4,
        maxCount: 5,
        threshold: 8,
        icon: LucidePersonStanding,
      },
      scientists: {
        name: "Scientists",
        description: "Add more scientists to speed up research.",
        cost: 16500,
        multiplier: 0.55,
        maxCount: 4,
        threshold: 12,
        icon: LucideMicroscope,
      },
      fuel_efficiency: {
        name: "Fuel Efficiency",
        description:
          "Optimize fuel usage allowing for longer exploration missions.",
        cost: 22500,
        multiplier: 0.7,
        maxCount: 3,
        threshold: 16,
        icon: LucideBatteryCharging,
      },
    },
  },
  spaceStation: {
    name: "Space Station",
    description: "Construct a space station to serve as a hub for operations.",
    baseCost: 20000,
    costMultiplier: 1.11,
    auPerSecond: 35,
    threshold: 8000,
    buildTime: 30,
    icon: LucideBuilding2,
    mapPosition: {
      x: 39,
      y: 58,
    },
    upgrades: {
      livingQuarters: {
        name: "Living Quarters",
        description: "Expand the space station to accommodate more crew.",
        cost: 27500,
        multiplier: 0.3,
        maxCount: 5,
        threshold: 4,
        icon: LucideBed,
      },
      researchLab: {
        name: "Research Labs",
        description:
          "Improve scientific research and technological advancements.",
        cost: 45000,
        multiplier: 0.45,
        maxCount: 5,
        threshold: 8,
        icon: LucideMicroscope,
      },
      defenseSystem: {
        name: "Defense Systems",
        description: "Protect the station from asteroids and other threats.",
        cost: 68000,
        multiplier: 0.6,
        maxCount: 3,
        threshold: 12,
        icon: LucideShieldAlert,
      },
      artificial_gravity: {
        name: "Artificial Gravity",
        description:
          "Install artificial gravity systems for increased comfort and efficiency.",
        cost: 90000,
        multiplier: 0.75,
        maxCount: 2,
        threshold: 16,
        icon: LucideRotate3D,
      },
    },
  },
  terraforming: {
    name: "Terraforming Project",
    description: "Transform a barren planet into a habitable world.",
    baseCost: 45000,
    costMultiplier: 1.12,
    auPerSecond: 60,
    threshold: 20000,
    icon: LucideMountain,
    buildTime: 45,
    mapPosition: {
      x: 36,
      y: 52,
    },
    upgrades: {
      atmosphereGenerators: {
        name: "Atmosphere Generators",
        description: "Accelerate the creation of a breathable atmosphere.",
        cost: 20000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideWind,
      },
      waterPurification: {
        name: "Water Purification Plants",
        description: "Ensure a clean and sustainable water supply.",
        cost: 27500,
        multiplier: 0.4,
        maxCount: 5,
        threshold: 8,
        icon: LucideDroplet,
      },
      ecoSystem: {
        name: "Ecosystem Development",
        description: "Introduce flora and fauna to the new world.",
        cost: 36000,
        multiplier: 0.65,
        maxCount: 3,
        threshold: 12,
        icon: LucideLeaf,
      },
      climate_control: {
        name: "Climate Control Systems",
        description:
          "Advanced technology to regulate and stabilize planetary weather patterns.",
        cost: 50000,
        multiplier: 0.8,
        maxCount: 2,
        threshold: 16,
        icon: LucideThermometer,
      },
    },
  },
  colonization: {
    name: "Colonize a Planet",
    description: "Assist mankind in colonizing a new planet.",
    baseCost: 75000,
    costMultiplier: 1.12,
    auPerSecond: 100,
    threshold: 40000,
    icon: LucideTentTree,
    buildTime: 60,
    mapPosition: {
      x: 36,
      y: 45,
    },
    upgrades: {
      buildings: {
        name: "Buildings",
        description: "Construct additional buildings to house more people.",
        cost: 115000,
        multiplier: 0.3,
        maxCount: 3,
        threshold: 4,
        icon: LucideBuilding,
      },
      houses: {
        name: "Houses",
        description: "Build more houses, offering room for population growth.",
        cost: 160000,
        multiplier: 0.4,
        maxCount: 5,
        threshold: 8,
        icon: LucideHouse,
      },
      hospitals: {
        name: "Hospitals",
        description: "Provide medical facilities to ensure population health.",
        cost: 205000,
        multiplier: 0.5,
        maxCount: 3,
        threshold: 12,
        icon: LucideHospital,
      },
      church: {
        name: "Churches",
        description: "Everyone needs something to believe in, right?",
        cost: 250000,
        multiplier: 0.65,
        maxCount: 2,
        threshold: 20,
        icon: LucideChurch,
      },
      education: {
        name: "Education Centers",
        description:
          "Build schools and universities to advance colony knowledge.",
        cost: 320000,
        multiplier: 0.85,
        maxCount: 3,
        threshold: 28,
        icon: LucideGraduationCap,
      },
      stori: {
        name: "Stori Beans",
        description: "The queen of the world!",
        cost: 420000,
        multiplier: 1.1,
        maxCount: 1,
        threshold: 40,
        icon: LucideCrown,
      },
    },
  },
  spaceElevator: {
    name: "Space Elevator",
    description: "Build a space elevator to drastically reduce launch costs.",
    baseCost: 160000,
    costMultiplier: 1.12,
    auPerSecond: 170,
    threshold: 65000,
    icon: LucideCableCar,
    buildTime: 90,
    mapPosition: {
      x: 40,
      y: 38,
    },
    upgrades: {
      cableMaterial: {
        name: "Advanced Cable Materials",
        description:
          "Enhance the strength and durability of the elevator cable.",
        cost: 230000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideLink,
      },
      cargoCapacity: {
        name: "Cargo Capacity",
        description:
          "Increase the amount of materials that can be transported.",
        cost: 320000,
        multiplier: 0.4,
        maxCount: 5,
        threshold: 8,
        icon: LucideBoxes,
      },
      safetyProtocols: {
        name: "Enhanced Safety Protocols",
        description: "Minimize the risks of catastrophic failure.",
        cost: 460000,
        multiplier: 0.55,
        maxCount: 3,
        threshold: 12,
        icon: LucideShieldCheck,
      },
      maintenance_drones: {
        name: "Maintenance Drone Fleet",
        description:
          "Automated drones that continuously inspect and repair the elevator structure.",
        cost: 600000,
        multiplier: 0.75,
        maxCount: 3,
        threshold: 20,
        icon: LucideCode,
      },
    },
  },
  warpDrive: {
    name: "Warp Drive",
    description: "Develop warp drive technology for faster-than-light travel.",
    baseCost: 750000,
    costMultiplier: 1.12,
    auPerSecond: 350,
    threshold: 220000,
    buildTime: 100,
    icon: LucideBolt,
    mapPosition: {
      x: 46,
      y: 34,
    },
    upgrades: {
      energySource: {
        name: "Advanced Energy Source",
        description:
          "Power the warp drive with a highly efficient energy core.",
        cost: 1100000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideBatteryCharging,
      },
      navigationSystem: {
        name: "Quantum Navigation System",
        description: "Navigate through space with pinpoint accuracy.",
        cost: 1450000,
        multiplier: 0.45,
        maxCount: 5,
        threshold: 8,
        icon: LucideCompass,
      },
      stabilizers: {
        name: "Warp Field Stabilizers",
        description: "Ensure a smooth and stable warp travel experience.",
        cost: 2200000,
        multiplier: 0.65,
        maxCount: 3,
        threshold: 12,
        icon: LucideRotate3D,
      },
      temporal_shielding: {
        name: "Temporal Shielding",
        description:
          "Advanced technology to protect crew from time dilation effects.",
        cost: 2800000,
        multiplier: 0.85,
        maxCount: 2,
        threshold: 20,
        icon: LucideShield,
      },
    },
  },
  orbitalRing: {
    name: "Orbital Ring",
    description:
      "Construct an orbital ring-3 around the planet for enhanced logistics.",
    baseCost: 2200000,
    costMultiplier: 1.12,
    auPerSecond: 550,
    threshold: 680000,
    icon: LucideCircleDot,
    buildTime: 120,
    mapPosition: {
      x: 55,
      y: 33,
    },
    upgrades: {
      constructionMaterials: {
        name: "Advanced Construction Materials",
        description: "Enhance the durability and longevity of the ring.",
        cost: 3700000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideLayers,
      },
      transportNetwork: {
        name: "Efficient Transport Network",
        description: "Increase the capacity and speed of material transport.",
        cost: 5200000,
        multiplier: 0.45,
        maxCount: 5,
        threshold: 8,
        icon: LucideTrain,
      },
      defenseGrid: {
        name: "Orbital Defense Grid",
        description: "Protect the ring-3 from potential threats.",
        cost: 7500000,
        multiplier: 0.65,
        maxCount: 3,
        threshold: 12,
        icon: LucideShieldCheck,
      },
      energy_stations: {
        name: "Solar Energy Stations",
        description:
          "Install massive solar arrays to power both the ring and planet below.",
        cost: 9200000,
        multiplier: 0.8,
        maxCount: 3,
        threshold: 20,
        icon: LucideSun,
      },
    },
  },
  quantumComputer: {
    name: "Quantum Computer",
    description: "Develop a quantum computer to perform advanced calculations.",
    baseCost: 5500000,
    costMultiplier: 1.12,
    auPerSecond: 700,
    threshold: 1350000,
    icon: LucideCpu,
    buildTime: 110,
    mapPosition: {
      x: 63,
      y: 37,
    },
    upgrades: {
      qubits: {
        name: "Qubit Expansion",
        description: "Increase the computational power with more qubits.",
        cost: 7500000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideBox,
      },
      coolingSystem: {
        name: "Advanced Cooling System",
        description: "Improve the stability and efficiency of the computer.",
        cost: 11000000,
        multiplier: 0.45,
        maxCount: 5,
        threshold: 8,
        icon: LucideThermometer,
      },
      algorithms: {
        name: "Optimized Algorithms",
        description: "Enhance the processing speed with better algorithms.",
        cost: 18500000,
        multiplier: 0.65,
        maxCount: 3,
        threshold: 12,
        icon: LucideCode,
      },
      quantum_entanglement: {
        name: "Quantum Entanglement Network",
        description:
          "Harness quantum entanglement for instantaneous data transfer.",
        cost: 23000000,
        multiplier: 0.9,
        maxCount: 2,
        threshold: 20,
        icon: LucideLink,
      },
    },
  },
  stargate: {
    name: "Stargate",
    description: "Build a Stargate to instantly travel between distant points.",
    baseCost: 11000000,
    costMultiplier: 1.12,
    auPerSecond: 950,
    threshold: 2800000,
    icon: LucideDoorOpen,
    buildTime: 110,
    mapPosition: {
      x: 68,
      y: 45,
    },
    upgrades: {
      portalStabilization: {
        name: "Portal Stabilization",
        description: "Reduce the risk of unstable portal openings.",
        cost: 15000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideWind,
      },
      powerSupply: {
        name: "Enhanced Power Supply",
        description: "Ensure continuous power for smooth portal operation.",
        cost: 22000000,
        multiplier: 0.45,
        maxCount: 5,
        threshold: 8,
        icon: LucideBatteryCharging,
      },
      networkExpansion: {
        name: "Network Expansion",
        description: "Increase the number of connected destinations.",
        cost: 36000000,
        multiplier: 0.65,
        maxCount: 3,
        threshold: 12,
        icon: LucideNetwork,
      },
      dimension_gate: {
        name: "Dimensional Gateway",
        description:
          "Unlock access to parallel dimensions with untapped resources.",
        cost: 55000000,
        multiplier: 0.9,
        maxCount: 2,
        threshold: 20,
        icon: LucideDoorOpen,
      },
    },
  },
  fusionReactor: {
    name: "Fusion Reactor",
    description:
      "Harness the power of fusion to generate vast amounts of energy.",
    baseCost: 18000000,
    costMultiplier: 1.12,
    auPerSecond: 1200,
    threshold: 4500000,
    buildTime: 130,
    icon: LucideAtom,
    mapPosition: {
      x: 69,
      y: 54,
    },
    upgrades: {
      fuelEfficiency: {
        name: "Fuel Efficiency",
        description: "Optimize the use of fusion fuel for more output.",
        cost: 22000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideDroplet,
      },
      magneticContainment: {
        name: "Magnetic Containment",
        description:
          "Improve the stability of the reactor's containment field.",
        cost: 33000000,
        multiplier: 0.5,
        maxCount: 5,
        threshold: 8,
        icon: LucideMagnet,
      },
      heatDissipation: {
        name: "Heat Dissipation",
        description: "Enhance cooling systems to handle higher energy output.",
        cost: 44000000,
        multiplier: 0.65,
        maxCount: 3,
        threshold: 12,
        icon: LucideThermometer,
      },
      plasma_containment: {
        name: "Advanced Plasma Containment",
        description:
          "Revolutionary technology for sustaining higher energy densities.",
        cost: 55000000,
        multiplier: 0.85,
        maxCount: 2,
        threshold: 20,
        icon: LucideShieldCheck,
      },
    },
  },
  starshipFleet: {
    name: "Starship Fleet",
    description: "Assemble a fleet of starships for exploration and defense.",
    baseCost: 35000000,
    costMultiplier: 1.12,
    auPerSecond: 1400,
    threshold: 9000000,
    icon: LucideShip,
    buildTime: 180,
    mapPosition: {
      x: 65,
      y: 63,
    },
    upgrades: {
      fleetSize: {
        name: "Expand Fleet Size",
        description: "Increase the number of starships in your fleet.",
        cost: 50000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideBox,
      },
      weaponSystems: {
        name: "Advanced Weapon Systems",
        description: "Equip your fleet with cutting-edge weaponry.",
        cost: 72000000,
        multiplier: 0.5,
        maxCount: 5,
        threshold: 8,
        icon: LucideSword,
      },
      shieldGenerators: {
        name: "Shield Generators",
        description: "Enhance the fleet's defensive capabilities.",
        cost: 110000000,
        multiplier: 0.7,
        maxCount: 3,
        threshold: 12,
        icon: LucideShield,
      },
      crew_training: {
        name: "Elite Crew Training",
        description:
          "Train your fleet crews in advanced tactics and operations.",
        cost: 138000000,
        multiplier: 0.85,
        maxCount: 2,
        threshold: 20,
        icon: LucideGraduationCap,
      },
    },
  },
  wormholeGenerator: {
    name: "Wormhole Generator",
    description: "Create wormholes to traverse vast distances instantly.",
    baseCost: 55000000,
    costMultiplier: 1.12,
    auPerSecond: 2200,
    threshold: 18000000,
    icon: LucideHouse,
    buildTime: 210,
    mapPosition: {
      x: 57,
      y: 70,
    },
    upgrades: {
      generatorStability: {
        name: "Generator Stability",
        description: "Reduce the risk of wormhole collapse.",
        cost: 75000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideWind,
      },
      destinationAccuracy: {
        name: "Destination Accuracy",
        description: "Increase the precision of wormhole exits.",
        cost: 110000000,
        multiplier: 0.55,
        maxCount: 5,
        threshold: 8,
        icon: LucideMapPin,
      },
      energyEfficiency: {
        name: "Energy Efficiency",
        description: "Optimize energy consumption for sustained operation.",
        cost: 150000000,
        multiplier: 0.75,
        maxCount: 3,
        threshold: 12,
        icon: LucideBatteryCharging,
      },
      wormhole_network: {
        name: "Wormhole Network",
        description:
          "Create multiple interconnected wormholes for a transportation network.",
        cost: 185000000,
        multiplier: 0.9,
        maxCount: 2,
        threshold: 20,
        icon: LucideNetwork,
      },
    },
  },
  orbitalCity: {
    name: "Orbital City",
    description: "Construct a city in orbit to house millions of people.",
    baseCost: 72000000,
    costMultiplier: 1.12,
    auPerSecond: 2700,
    threshold: 22000000,
    icon: LucideCastle,
    buildTime: 230,
    mapPosition: {
      x: 47,
      y: 72,
    },
    upgrades: {
      populationCapacity: {
        name: "Expand Population Capacity",
        description: "Increase the city's capacity to house more residents.",
        cost: 110000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideBuilding,
      },
      energyGrid: {
        name: "Advanced Energy Grid",
        description: "Improve the city's energy efficiency and output.",
        cost: 145000000,
        multiplier: 0.55,
        maxCount: 5,
        threshold: 8,
        icon: LucideBattery,
      },
      transportationNetwork: {
        name: "Efficient Transportation Network",
        description: "Enhance the city's internal transportation systems.",
        cost: 220000000,
        multiplier: 0.75,
        maxCount: 3,
        threshold: 12,
        icon: LucideTrain,
      },
      life_support: {
        name: "Advanced Life Support Systems",
        description:
          "Cutting-edge technology to maintain perfect living conditions.",
        cost: 275000000,
        multiplier: 0.95,
        maxCount: 2,
        threshold: 20,
        icon: LucideDroplet,
      },
    },
  },
  intergalacticProbe: {
    name: "Intergalactic Probe",
    description: "Launch a probe to explore other galaxies.",
    baseCost: 110000000,
    costMultiplier: 1.12,
    auPerSecond: 3300,
    threshold: 45000000,
    icon: LucideCompass,
    buildTime: 250,
    mapPosition: {
      x: 36,
      y: 68,
    },
    upgrades: {
      sensorArray: {
        name: "Advanced Sensor Array",
        description: "Improve the probe's data collection capabilities.",
        cost: 150000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideRadar,
      },
      propulsionSystem: {
        name: "High-Efficiency Propulsion System",
        description: "Increase the probe's travel speed.",
        cost: 225000000,
        multiplier: 0.55,
        maxCount: 5,
        threshold: 8,
        icon: LucideArrowRight,
      },
      dataTransmission: {
        name: "Quantum Data Transmission",
        description: "Enhance the probe's ability to send data back quickly.",
        cost: 375000000,
        multiplier: 0.75,
        maxCount: 3,
        threshold: 12,
        icon: LucideSignal,
      },
      ai_navigation: {
        name: "AI Navigation System",
        description:
          "Self-learning AI that discovers optimal exploration paths.",
        cost: 470000000,
        multiplier: 0.95,
        maxCount: 2,
        threshold: 20,
        icon: LucideCode,
      },
    },
  },
  matterSynthesizer: {
    name: "Matter Synthesizer",
    description: "Synthesize raw materials from energy.",
    baseCost: 145000000,
    costMultiplier: 1.12,
    auPerSecond: 4000,
    threshold: 68000000,
    icon: LucideAnvil,
    buildTime: 280,
    mapPosition: {
      x: 29,
      y: 60,
    },
    upgrades: {
      energyConversion: {
        name: "Energy Conversion Efficiency",
        description: "Improve the efficiency of matter synthesis.",
        cost: 185000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideBattery,
      },
      materialPurity: {
        name: "Material Purity Enhancement",
        description: "Increase the quality of synthesized materials.",
        cost: 260000000,
        multiplier: 0.55,
        maxCount: 5,
        threshold: 8,
        icon: LucideGem,
      },
      productionRate: {
        name: "Accelerated Production",
        description: "Boost the rate of material synthesis.",
        cost: 370000000,
        multiplier: 0.75,
        maxCount: 3,
        threshold: 12,
        icon: LucideClock,
      },
      nano_assembly: {
        name: "Nano-Scale Assembly",
        description:
          "Molecular fabrication technology for perfect atomic structure.",
        cost: 470000000,
        multiplier: 1.0,
        maxCount: 2,
        threshold: 20,
        icon: LucideLayers,
      },
    },
  },
  timeDilationDevice: {
    name: "Time Dilation Device",
    description: "Manipulate time to accelerate progress.",
    baseCost: 220000000,
    costMultiplier: 1.12,
    auPerSecond: 5000,
    threshold: 90000000,
    icon: LucideClock,
    buildTime: 320,
    mapPosition: {
      x: 26,
      y: 48,
    },
    upgrades: {
      temporalStability: {
        name: "Temporal Stability",
        description: "Improve the stability of time manipulation.",
        cost: 300000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideShield,
      },
      timeCompression: {
        name: "Time Compression",
        description: "Increase the effect of time dilation.",
        cost: 450000000,
        multiplier: 0.55,
        maxCount: 5,
        threshold: 8,
        icon: LucideFastForward,
      },
      energyConservation: {
        name: "Energy Conservation",
        description: "Optimize energy usage during time manipulation.",
        cost: 600000000,
        multiplier: 0.75,
        maxCount: 3,
        threshold: 12,
        icon: LucideBattery,
      },
      time_loop: {
        name: "Temporal Loop System",
        description:
          "Create localized time loops for exponential productivity gains.",
        cost: 750000000,
        multiplier: 1.05,
        maxCount: 2,
        threshold: 20,
        icon: LucideRotate3D,
      },
    },
  },
  DysonSphere: {
    name: "Dyson Sphere",
    description: "Construct a Dyson Sphere to harness the power of a star.",
    baseCost: 380000000,
    costMultiplier: 1.12,
    auPerSecond: 7000,
    threshold: 180000000,
    buildTime: 360,
    icon: LucideSun,
    mapPosition: {
      x: 29,
      y: 36,
    },
    upgrades: {
      solarCollectors: {
        name: "Advanced Solar Collectors",
        description: "Increase energy collection efficiency.",
        cost: 450000000,
        multiplier: 0.3,
        maxCount: 8,
        threshold: 4,
        icon: LucideBatteryCharging,
      },
      energyStorage: {
        name: "High-Capacity Energy Storage",
        description: "Store excess energy for later use.",
        cost: 675000000,
        multiplier: 0.55,
        maxCount: 5,
        threshold: 8,
        icon: LucideShield,
      },
      stabilityEnhancements: {
        name: "Structural Stability Enhancements",
        description: "Ensure the Dyson Sphere remains stable over time.",
        cost: 900000000,
        multiplier: 0.85,
        maxCount: 3,
        threshold: 12,
        icon: LucideTableCellsSplit,
      },
      matrioshka_brain: {
        name: "Matrioshka Brain",
        description:
          "Add computational layers to transform your Dyson Sphere into a massive computer.",
        cost: 1100000000,
        multiplier: 1.25,
        maxCount: 1,
        threshold: 24,
        icon: LucideCpu,
      },
    },
  },
};
