export const EQUIPMENT_RATE = 1000;

export const EQUIPMENT_RATE_DELTA = 33;

export const EQUIPMENT_RATE_MINIMUM = 16.66;

export const EQUIPMENT_RATE_REDUCTION = 0;

export const EQUIPMENT_RATE_REDUCTION_DELTA = 1;
