import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Dev } from "@/providers/jotai-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative h-lvh w-screen overflow-x-hidden">
          {children}
          <Dev />
        </main>
      </body>
    </html>
  );
}
